name: NotTheServersFault
version: 1.1.1
main: xyz.vprolabs.nottheserversfault.NotTheServersFault
api-version: '1.21'
description: A chaotic challenge for 1.21.x (1.21 - 1.21.11) on Bukkit, Spigot, Paper, and Purpur. Report bugs at discord.gg/SNzUYWbc5Q
softdepend: [packetevents, chunky]
commands:
  start:
    description: Start the game
    usage: /start
  ntsf:
    description: Admin commands
    usage: /ntsf <vanish>
    aliases: [nottheserversfault]
    permission: ntsf.admin
